# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://ksamafybltajrgrhmgzw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzYW1hZnlibHRhanJncmhtZ3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDIzNDgzOTIsImV4cCI6MjAxNzkyNDM5Mn0.MIBSPCNyXHc45nmKneZewUzDDRU4mh9-NyUKI_beR50"

